#!/bin/zsh

if [ "$#" -ne 1 ]; then
    echo "please provide path to target repo, e.g., './sync-milestones ../go-tableland'"
    exit 1
fi
(cd $1 && echo "Syncing milestones in $PWD")

declare -A existing
list=$(cd $1 && gh milestone list --state all --output json)
ret=$?
if [[ $ret -ne 0 ]]; then
  echo >&2 $list
  exit 1
fi
if [[ "$list" != "[]" ]]; then
  echo $list |
    jq '.[] | with_entries(select([.key] | inside(["Number", "Title"])))' |
    jq -s -r '(.[0] | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' |
    tail -n +2 |
    tr -d '"' > .list.csv
  while IFS=, read -r number title
  do
    existing[$title]=$number
  done < .list.csv
  rm .list.csv
fi

while IFS=, read -r title date
do
  create=$(cd $1 && gh milestone create --title ${title} --due-date ${date})
  ret=$?
  if [[ $ret -ne 0 ]]; then
    if [[ "$create" == *"already exists"* ]]; then
      edit=$(cd $1 && gh milestone edit ${existing[$title]} --due-date ${date})
      ret=$?
      if [[ $ret -ne 0 ]]; then
        echo >&2 $edit
        exit 1
      fi  
    else
      echo >&2 $create
      exit 1
    fi
  fi
  echo "Synced milestone ${title} with due date ${date}"
done < milestones.csv
